### ISSUE TITLE
java.net.SocketException: Connection reset by peer: socket write error

### ISSUE THREAD

**Issue by mushanwb** [mushanwb/socket#1]
每当有客户端下线的时候，总会抛出：java.net.SocketException: Connection reset by peer: socket write error

> JDK版本： 1.8 
> 系统：windows

```java
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.io.BufferedReader.readLine(BufferedReader.java:324)
	at java.io.BufferedReader.readLine(BufferedReader.java:389)
	at com.github.mushanwb.ClientConnection.run(ClientConnection.java:48)
Exception in thread "Thread-0" java.lang.RuntimeException: java.net.SocketException: Connection reset by peer: socket write error
	at com.github.mushanwb.Server.dispatchMessage(Server.java:106)
	at com.github.mushanwb.Server.lambda$clientOffline$2(Server.java:93)
	at java.util.concurrent.ConcurrentHashMap$ValuesView.forEach(ConcurrentHashMap.java:4707)
	at com.github.mushanwb.Server.clientOffline(Server.java:93)
	at com.github.mushanwb.ClientConnection.run(ClientConnection.java:64)
Caused by: java.net.SocketException: Connection reset by peer: socket write error
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:143)
	at com.github.mushanwb.ClientConnection.sendMessage(ClientConnection.java:73)
	at com.github.mushanwb.Server.dispatchMessage(Server.java:104)
	... 4 more
```
@blindpirate   请博大有空能帮我看一下不？？求解

**Comment by blindpirate** [comment]
https://github.com/mushanwb/socket/blob/main/src/main/java/com/github/mushanwb/Server.java#L93

这里的`clientConnection`是刚刚下线（断开）的那个Socket，你为啥还要给这个socket发信息？你应该给“其余在线的Socket（用户）”发信息。

**Comment by blindpirate** [comment]
你给出的stacktrace的最后一行清楚无误地告诉你，错误发生在哪个类的哪一行：

```
at com.github.mushanwb.Server.dispatchMessage(Server.java:104)
```

**Comment by mushanwb** [comment]
@blindpirate 感觉博大，发现问题原因了，发送消息的对象搞混了
